#(8)(a)
college = read.csv("College.csv", na.strings = "?", stringsAsFactors = T)
#(8)(b)
rownames(college) <- college[, 1]
View(college)
college <- college[, -1]
View(college)
#(8)(c)(I)
summary(college)
#(8)(c)(II)
pairs(college)
college[,1:10]
#(8)(c)(III)
plot(college$Private, college$Outstate)
#(8)(c)(IV)
Elite <- rep("No", nrow(college))
Elite[college$Top10perc > 50] = "Yes"
Elite <- as.factor(Elite)
college <- data.frame(college, Elite)
summary(college$Elite)
plot(college$Elite, college$Outstate)
#(8)(c)(V)
par(mfrow = c(2, 2))
hist(college$Enroll, col = 5)
hist(college$Accept, col=2)
hist(college$Grad.Rate, col=3)
hist(college$F.Undergrad, col = 4)
#(8)(c)(VI)
par(mfrow=c(1,2))
plot(college$Outstate, college$Grad.Rate)
plot(college$Apps, college$Enroll)
